### ISSUE TITLE
android.security.KeyChainException: java.lang.IllegalStateException: keystore is UNINITIALIZED

### ISSUE THREAD

**Issue by jbreon** [Miserlou/Android-SDK-Samples#1]
When I import to Android Studio the KeyChainDemoActivity I get the following when running to device:

04-21 12:49:41.917      345-345/com.example.android.keychain D/OpenGLRenderer﹕ Enabling debug mode 0
04-21 12:49:42.107      345-365/com.example.android.keychain W/System.err﹕ android.security.KeyChainException: java.lang.IllegalStateException: keystore is UNINITIALIZED
04-21 12:49:42.107      345-365/com.example.android.keychain W/System.err﹕ at android.security.KeyChain.getCertificateChain(KeyChain.java:356)
04-21 12:49:42.107      345-365/com.example.android.keychain W/System.err﹕ at com.example.android.keychain.KeyChainDemoActivity.getCertificateChain(KeyChainDemoActivity.java:264)
04-21 12:49:42.107      345-365/com.example.android.keychain W/System.err﹕ at com.example.android.keychain.KeyChainDemoActivity.isKeyChainAccessible(KeyChainDemoActivity.java:290)
04-21 12:49:42.107      345-365/com.example.android.keychain W/System.err﹕ at com.example.android.keychain.KeyChainDemoActivity.access$000(KeyChainDemoActivity.java:39)
04-21 12:49:42.107      345-365/com.example.android.keychain W/System.err﹕ at com.example.android.keychain.KeyChainDemoActivity$1.run(KeyChainDemoActivity.java:98)
04-21 12:49:42.107      345-365/com.example.android.keychain W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
04-21 12:49:42.107      345-365/com.example.android.keychain W/System.err﹕ Caused by: java.lang.IllegalStateException: keystore is UNINITIALIZED
04-21 12:49:42.107      345-365/com.example.android.keychain W/System.err﹕ at android.os.Parcel.readException(Parcel.java:1469)
04-21 12:49:42.107      345-365/com.example.android.keychain W/System.err﹕ at android.os.Parcel.readException(Parcel.java:1415)
04-21 12:49:42.107      345-365/com.example.android.keychain W/System.err﹕ at android.security.IKeyChainService$Stub$Proxy.getCertificate(IKeyChainService.java:170)
04-21 12:49:42.107      345-365/com.example.android.keychain W/System.err﹕ at android.security.KeyChain.getCertificateChain(KeyChain.java:341)
04-21 12:49:42.107      345-365/com.example.android.keychain W/System.err﹕ ... 5 more
04-21 12:49:42.107      345-365/com.example.android.keychain D/KeyChainApiActivity﹕ Key Chain is not accessible

**Comment by jbreon** [comment]
A dialog appears that asks for a password to extract from My Keychain that confused as I was watching debug. Sorry

**Comment by jbreon** [comment]
This is a excellent working example...Thanks!
